name: viemo
description: A Movie Flutter App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  dio: ^5.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^9.1.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  infinite_scroll_pagination: ^3.2.0
  intl: any
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
